/*
Five-Letters Guessing Game
Copyright (C) 2026  Max Parkhomenko

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
public static class Wordlist
{
    public static readonly string[] words = [
        "арбуз",
        "армия",
        "банан",
        "берег",
        "билет",
        "бочка",
        "ветка",
        "вишня",
        "весна",
        "волна",
        "город",
        "груша",
        "дверь",
        "диван",
        "дождь",
        "драка",
        "доска",
        "жираф",
        "замок",
        "зебра",
        "земля",
        "игрок",
        "индюк",
        "кабан",
        "капля",
        "карта",
        "каюта",
        "кисть",
        "книга",
        "ковер",
        "колос",
        "комар",
        "конец",
        "копье",
        "кошка",
        "крыло",
        "лампа",
        "лилия",
        "лимон",
        "лодка",
        "ложка",
        "магия",
        "маска",
        "месяц",
        "метро",
        "мечта",
        "мышка",
        "носок",
        "недуг",
        "обмен",
        "океан",
        "олень",
        "палец",
        "песня",
        "петух",
        "пирог",
        "пламя",
        "плечо",
        "полка",
        "птица",
        "пушка",
        "радар",
        "рукав",
        "рынок",
        "салат",
        "сапог",
        "свеча",
        "серия",
        "скала",
        "сквер",
        "скрип",
        "слеза",
        "слово",
        "снега",
        "сокол",
        "сосна",
        "спина",
        "стена",
        "столб",
        "сумка",
        "тайга",
        "танец",
        "топор",
        "трава",
        "труба",
        "тунец",
        "тыква",
        "уголь",
        "улица",
        "фрукт",
        "халат",
        "цапля",
        "чайка",
        "череп",
        "шапка",
        "школа",
        "шпион",
        "шприц",
        "щенок",
        "экран",
        "юноша",
        "ягода"
    ];
}